spring:
  profiles:
    active:
      - dev
      - fillTestData
  data:
    rest:
      # all urls are prepended by /api. We will have in same domain frontend, thus no clash with api should be maintained
      base-path: /api
logging.level.org.zalando.logbook: TRACE
server:
  port: 8080
  use-forward-headers: true
---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
debug: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
